"""
This module provides a password generator tool called PyPass.

Functions:
- generate_password: Generates a password based on user preferences.
- main: Handles user input and generates a password interactively.
"""


import random  # random number generator
import string


def generate_password(length=20,  # Generates the password
                      use_uppercase=True,
                      use_numbers=True,
                      use_unique=True,
                      longlength=True):

    characters = string.ascii_lowercase
    if use_uppercase:
        characters += string.ascii_uppercase
    if use_numbers:
        characters += string.digits
    if use_unique:
        characters += string.punctuation

    if not longlength and length > 20:
        raise ValueError(
            "Password Length cannot be more than 20 characters when you have not chosen the LongLength Value")
    if length < 4:
        raise ValueError("Password must be minimum to 4 characters")

    password = ''.join(random.choice(characters) for _ in range(length))
    return password


def main():  # asks the User Questions and feeds the data to the password generator.
    print("hello, welcome to PyPass!")
    try:
        longlength = input(
        "By Default, Passwords generated by Pypass are restricted to a maximum of 20 characters."
        "if you'd like to enable Longer passwords,"
        "you can enable MaxPass to have longer passwords."
        "If you'd like this option, Press Y and Enter. "
        "Otherwise, Press N and Enter: "
        ).strip().lower()

        if longlength not in ['y', 'n']:
            raise ValueError(
                "invalid input, Please Enter 'y' for yes, or 'n' for no. : ")
        if longlength == 'y':
            print("MaxPass is Enabled, Enjoy!")
        else:
            print("Alrighty, MaxPass is still disabled.")

        length = int(
            input("What length would you like your password to be?: "))

        if not longlength and length > 20:
            raise ValueError(
                "Password cannot be more than 20 characters if MaxPass is not enabled")
        if length < 4:
            raise ValueError(
                "Password has to be a minimum of 4 characters and a Maximum of 20.")

        use_uppercase = input(
            "Alright, would you like to include uppercase letters? (y/n): ").strip().lower() == 'y'
        use_numbers = input(
            "Almost There, would you like to include numbers? (y/n): ").strip().lower() == 'y'
        use_unique = input(
            "Finally, would you Include Special Characters? (y/n): ").strip().lower() == 'y'

        # generate password
        password = generate_password(
            length, use_uppercase, use_numbers, use_unique, longlength)
        print(f"Your generated password is: {password}")
    except ValueError as e:
        print(f"Error: {e}")


if __name__ == "__main__":
    main()
